### ISSUE TITLE
[DEFCON 31] Peer Code Review

### ISSUE THREAD

**Issue by terrancedejesus** [elastic/SWAT#24]
Let's use this issue to track our peer code review and revisions. Following the task, we can turn any into another issue/pr if the peer review warrants it.

```[tasklist]
### Tasks
- [ ] https://github.com/elastic/SWAT/issues/25
- [ ] https://github.com/elastic/SWAT/issues/42
- [x] [Maintenance] Review SWAT core `shell.py` and `main.py`
- [ ] https://github.com/elastic/SWAT/issues/26
- [x] [Maintenance] Review SWAT Commands `base_command.py`
- [ ] https://github.com/elastic/SWAT/issues/27
- [ ] https://github.com/elastic/SWAT/issues/28
- [x] [Maintenance] Review SWAT Emulations Module Instantiation
- [x] [Maintenance] Review SWAT Emulations `base_emulation.py`
- [ ] https://github.com/elastic/SWAT/issues/29
- [ ] https://github.com/elastic/SWAT/issues/30
- [ ] https://github.com/elastic/SWAT/issues/32
- [ ] https://github.com/elastic/SWAT/issues/33
```
