### ISSUE TITLE
[Maintenance] Review SWAT logging `logger.py`

### ISSUE THREAD

**Issue by terrancedejesus** [elastic/SWAT#26]
## Overview
This issue is used to track adjustments to SWAT logging. The suggestions/tasks listed were discussed during a peer code review.

```[tasklist]
### Tasks
- [ ] Expose logging parameters to shell
- [ ] color for console and file logging
- [ ] add a logger for each module
```
