### ISSUE TITLE
[Maintenance] Review SWAT Authentication `authenticate.py`

### ISSUE THREAD

**Issue by terrancedejesus** [elastic/SWAT#27]
## Overview
This issue is used to track adjustments to the authentication workflow of SWAT. The suggestions/tasks listed were discussed during a peer code review.

Suggestions:

```[tasklist]
### Tasks
- [x] expose option to store access token and credentials or not
- [x] check for file or environment variable
- [x] Add missing `argparse` library
- [x] Add capability to authenticate with external Google account for adversary emulation
```
