### ISSUE TITLE
[Maintenance] Review SWAT Coverage `coverage.py`

### ISSUE THREAD

**Issue by terrancedejesus** [elastic/SWAT#29]
This issue is used to track adjustments to SWAT coverage command. The suggestions/tasks listed were discussed during a peer code review.

Suggestions:

```[tasklist]
### Tasks
- [ ] Show what we don't have coverage from for ATT&CK
- [ ] Be aware of potential changes based on folder structure for emulation modules
- [ ] Show ATT&CK version argument
```
