### ISSUE TITLE
[Maintenance] Review SWAT Data `data.py`

### ISSUE THREAD

**Issue by terrancedejesus** [elastic/SWAT#30]
## Overview
This issue is used to track adjustments to SWAT data command. The suggestions/tasks listed were discussed during a peer code review.

Suggestions:

```[tasklist]
### Tasks
- [x] rename to audit or events or logs
- [x] enable live audit logging from GWS
- [x] pipe or export data elsewhere (connectors)
- [x] add filter capabilities with pandas
- [x] add support to gracefully exit if `audit_support` not installed with poetry
```
